name: Zap
main: net.weasel.Zap.Zap
version: 1.0
commands:
  zap:
    description: Zap the blocks!
    usage: "Usage: /zap <block type id>"
    aliases: zapsurface
  zapfloor:
    description: Zap only floor blocks!
    usage: "Usage: /zapfloor <block type id>"
  zapceiling:
    description: Zap only ceiling blocks!
    usage: "Usage: /zapceiling <block type id>"
  zapwall:
    description: Zap only wall blocks!
    usage: "Usage: /zapwall <block type id>"
  zrl:
    description: Reload the Zap plugin
    usage: "Usage: /zrl"
  zstat:
    description: Shows the status of the Zap block operation
    usage: "Usage: /zstat"
